version: '2'
services:
  irpf:
    container_name: irpf
    image: rochacbruno/irpf
    environment:
      - DISPLAY
      - _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
    volumes:
      - ~/ProgramasRFB:/home/irpf/ProgramasRFB
